litellm_settings:
  request_timeout: 90000  # Увеличит таймаут до 1500 минут

model_list:
  - model_name: slowrig/coder
    litellm_params:
      model: openai/Qwen3.5-9B-UD-Q4_K_XL
      api_base: http://llama-coder:8080/v1
      api_key: dummy
      timeout: 90000
      stream_timeout: 90000
    model_info:
      max_tokens: 128000
      max_input_tokens: 55000
      max_output_tokens: 5000
      mode: chat

  - model_name: slowrig/architect
    litellm_params:
      model: openai/Qwen3.6-27B-UD-Q4_K_XL
      api_base: http://llama-architect:8080/v1
      api_key: dummy
      timeout: 90000
      stream_timeout: 90000
    model_info:
      max_tokens: 60000
      max_input_tokens: 55000
      max_output_tokens: 5000
      mode: chat
general_settings:
  store_model_in_db: false
  always_include_stream_usage: true
